### ISSUE TITLE
Inhaltsverzeichniseintrag für Listings fehlt

### ISSUE THREAD

**Issue by cschaf** [Sanguinik/template-wiss-arbeit#4]
Hallo, danke für dieses tolle Projekt/Vorlage. Leider fehlt im Inhaltsverzeichnis ein Eintrag  für Listings.

**Comment by cschaf** [comment]
Sorry das ich nerve aber habt ihr schon eine Lösung gefunden? Ich konnte leider den Fehler noch nicht finden.

**Comment by Sanguinik** [comment]
Hallo! Entschuldige bitte, ich bin noch  nicht dazu gekommen - setze mich jetzt daran und versuche das Problem schnellstmöglich zu beheben.
